name: Evaluate LaunchDarkly flags
on: push
jobs:
  eval-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate flags
        id: ld
        uses: launchdarkly/gha-flags@v1.0.1
        with:
          sdk-key: ${{ secrets.LAUNCHDARKLY_SDK_KEY }}
          flags: |
            animalPreference,cat
            showPreferenceButton,false
          
      - name: Branch on animalPreference == dog
        if: fromJSON(steps.ld.outputs.animalPreference) == 'dog'
        run: echo "🐶 Dog-first variation is active"

      - name: Branch on animalPreference == cat
        if: fromJSON(steps.ld.outputs.animalPreference) == 'cat'
        run: echo "🐱 Cat-first variation is active"

      - name: Branch on showPreferenceButton == true
        if: fromJSON(steps.ld.outputs.showPreferenceButton) == true
        run: echo "✅ Preference button will show"

      - name: Branch on showPreferenceButton == false
        if: fromJSON(steps.ld.outputs.showPreferenceButton) == false
        run: echo "🚫 Preference button hidden"
